// copy and paste this into the keymap.c file (which is autogenerated from
// the keymap, which doesn't include this by default)

// Disable backlight animations, just use solid color
void keyboard_post_init_user(void) {
    rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
    // Half brightness
    rgb_matrix_sethsv_noeeprom(0, 0, 64);
}

// Layer indicator on all keys
bool rgb_matrix_indicators_user(void) {
    // Brightness shared by all layers
    const uint8_t brightness = 64;
    switch(get_highest_layer(layer_state|default_layer_state)) {
        case 3:
            // Cyan
            rgb_matrix_sethsv_noeeprom(128, 255, brightness);
            break;
        case 2:
            // Red
            rgb_matrix_sethsv_noeeprom(0, 255, brightness);
            break;
        case 1:
            // Green
            rgb_matrix_sethsv_noeeprom(85, 255, brightness);
            break;
        default:
            // White
            rgb_matrix_sethsv_noeeprom(0, 0, brightness);
            break;
    }
    return false;
}

// Tap dance configuration to make the "enter" key work as an "opt" / "alt" key
// https://docs.qmk.fm/features/tap_dance#example-3
enum {
    // Enum for the "enter" key tap dance
    CT_ENT,
    // Enum for the "space" key tap dance
    CT_SPC,
    // Enum for the "quote" key tap dance
    CT_QUOT,
    // Enum for the "zero" key tap dance
    CT_P0
};

typedef struct {
    uint16_t tap;
    uint16_t hold;
    uint16_t held;
} tap_dance_tap_hold_t;

void tap_dance_tap_hold_finished(tap_dance_state_t *state, void *user_data) {
    tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)user_data;

    if (state->pressed) {
        if (state->count == 1
#ifndef PERMISSIVE_HOLD
            && !state->interrupted
#endif
        ) {
            register_code16(tap_hold->hold);
            tap_hold->held = tap_hold->hold;
        } else {
            register_code16(tap_hold->tap);
            tap_hold->held = tap_hold->tap;
        }
    }
}

void tap_dance_tap_hold_reset(tap_dance_state_t *state, void *user_data) {
    tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)user_data;

    if (tap_hold->held) {
        unregister_code16(tap_hold->held);
        tap_hold->held = 0;
    }
}

#define ACTION_TAP_DANCE_TAP_HOLD(tap, hold)                                        \
    {                                                                               \
        .fn        = {NULL, tap_dance_tap_hold_finished, tap_dance_tap_hold_reset}, \
        .user_data = (void *)&((tap_dance_tap_hold_t){tap, hold, 0}),               \
    }

tap_dance_action_t tap_dance_actions[] = {
    [CT_ENT] = ACTION_TAP_DANCE_TAP_HOLD(KC_ENT, KC_LGUI),
    [CT_SPC] = ACTION_TAP_DANCE_TAP_HOLD(KC_SPC, KC_RCMD),
    [CT_QUOT] = ACTION_TAP_DANCE_TAP_HOLD(KC_QUOT, KC_RCTL),
    [CT_P0] = ACTION_TAP_DANCE_TAP_HOLD(KC_P0, KC_RALT),
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    // Handle macros
    if (record->event.pressed) {
        switch (keycode) {
            case QK_MACRO_0:
                SEND_STRING(SS_DOWN(X_LSFT)SS_DOWN(X_LCMD)SS_TAP(X_LBRC)SS_UP(X_LCMD)SS_UP(X_LSFT));
                return false;
            case QK_MACRO_1:
                SEND_STRING(SS_DOWN(X_LSFT)SS_DOWN(X_LCMD)SS_TAP(X_RBRC)SS_UP(X_LCMD)SS_UP(X_LSFT));
                return false;
            case QK_MACRO_2:
                SEND_STRING(SS_DOWN(X_LCTL)SS_DOWN(X_LCMD)SS_TAP(X_LEFT)SS_UP(X_LCMD)SS_UP(X_LCTL));
                return false;
            case QK_MACRO_3:
                SEND_STRING(SS_DOWN(X_LCTL)SS_DOWN(X_LCMD)SS_TAP(X_RGHT)SS_UP(X_LCMD)SS_UP(X_LCTL));
                return false;
        }
    }

    // Handle tap dance
    switch (keycode) {
        case TD(CT_ENT): // list all tap dance keycodes with tap-hold configurations
        case TD(CT_SPC):
        case TD(CT_QUOT):
        case TD(CT_P0):
            if (!record->event.pressed) {
                uint8_t index = QK_TAP_DANCE_GET_INDEX(keycode);
                tap_dance_action_t *action = tap_dance_get(index);
                tap_dance_state_t *state = tap_dance_get_state(index);
                if (state != NULL && state->count && !state->finished) {
                    tap_dance_tap_hold_t *tap_hold = (tap_dance_tap_hold_t *)action->user_data;
                    tap_code16(tap_hold->tap);
                }
            }
            break;
    }

    return true;
};

// End tap dance configuration
