// copy and paste this into the keymap.c file (which is autogenerated from
// the keymap, which doesn't include this by default)

// Disable backlight animations, just use solid color
void keyboard_post_init_user(void) {
    rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
    // Half brightness
    rgb_matrix_sethsv_noeeprom(0, 0, 64);
}

// Layer indicator on all keys
bool rgb_matrix_indicators_user(void) {
    // Brightness shared by all layers
    const uint8_t brightness = 64;
    switch(get_highest_layer(layer_state|default_layer_state)) {
        case 3:
            // Green
            rgb_matrix_sethsv_noeeprom(85, 255, brightness);
            break;
        case 2:
            // Red
            rgb_matrix_sethsv_noeeprom(0, 255, brightness);
            break;
        case 1:
            // Cyan
            rgb_matrix_sethsv_noeeprom(128, 255, brightness);
            break;
        default:
            // White
            rgb_matrix_sethsv_noeeprom(0, 0, brightness);
            break;
    }
    return false;
}
