// copy and paste this into the keymap.c file (which is autogenerated from
// the keymap, which doesn't include this by default)

// Disable backlight animations, just use solid color
void keyboard_post_init_user(void) {
    rgb_matrix_mode_noeeprom(RGB_MATRIX_SOLID_COLOR);
    // Half brightness
    rgb_matrix_sethsv_noeeprom(0, 0, 128);
}
